// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ccex_api.Data;

#nullable disable

namespace ccex_api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241212012724_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChineseCharacterChineseCharacter", b =>
                {
                    b.Property<int>("ComponentsId")
                        .HasColumnType("integer");

                    b.Property<int>("DerivativesId")
                        .HasColumnType("integer");

                    b.HasKey("ComponentsId", "DerivativesId");

                    b.HasIndex("DerivativesId");

                    b.ToTable("ChineseCharacterChineseCharacter");
                });

            modelBuilder.Entity("ChineseCharacterPinyin", b =>
                {
                    b.Property<int>("AllPinyinId")
                        .HasColumnType("integer");

                    b.Property<int>("CharsId")
                        .HasColumnType("integer");

                    b.HasKey("AllPinyinId", "CharsId");

                    b.HasIndex("CharsId");

                    b.ToTable("ChineseCharacterPinyin");
                });

            modelBuilder.Entity("ccex_api.Models.ChineseCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Char")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<int?>("MainPinyinId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.HasIndex("Char")
                        .IsUnique();

                    b.HasIndex("MainPinyinId");

                    b.ToTable("ChineseCharacter");
                });

            modelBuilder.Entity("ccex_api.Models.Pinyin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Syllable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyllableWithToneMark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToneNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("TradCharacterStubId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SyllableWithToneMark")
                        .IsUnique();

                    b.HasIndex("TradCharacterStubId");

                    b.HasIndex("Syllable", "ToneNumber")
                        .IsUnique();

                    b.ToTable("Pinyin");
                });

            modelBuilder.Entity("ccex_api.Models.TradCharacterStub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Char")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("SimpCharId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SimpCharId");

                    b.ToTable("TradCharacterStub");
                });

            modelBuilder.Entity("ChineseCharacterChineseCharacter", b =>
                {
                    b.HasOne("ccex_api.Models.ChineseCharacter", null)
                        .WithMany()
                        .HasForeignKey("ComponentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ccex_api.Models.ChineseCharacter", null)
                        .WithMany()
                        .HasForeignKey("DerivativesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChineseCharacterPinyin", b =>
                {
                    b.HasOne("ccex_api.Models.Pinyin", null)
                        .WithMany()
                        .HasForeignKey("AllPinyinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ccex_api.Models.ChineseCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ccex_api.Models.ChineseCharacter", b =>
                {
                    b.HasOne("ccex_api.Models.ChineseCharacter", "Base")
                        .WithMany("Variants")
                        .HasForeignKey("BaseId");

                    b.HasOne("ccex_api.Models.Pinyin", "MainPinyin")
                        .WithMany()
                        .HasForeignKey("MainPinyinId");

                    b.Navigation("Base");

                    b.Navigation("MainPinyin");
                });

            modelBuilder.Entity("ccex_api.Models.Pinyin", b =>
                {
                    b.HasOne("ccex_api.Models.TradCharacterStub", null)
                        .WithMany("Pinyin")
                        .HasForeignKey("TradCharacterStubId");
                });

            modelBuilder.Entity("ccex_api.Models.TradCharacterStub", b =>
                {
                    b.HasOne("ccex_api.Models.ChineseCharacter", "SimpChar")
                        .WithMany("TradChars")
                        .HasForeignKey("SimpCharId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimpChar");
                });

            modelBuilder.Entity("ccex_api.Models.ChineseCharacter", b =>
                {
                    b.Navigation("TradChars");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("ccex_api.Models.TradCharacterStub", b =>
                {
                    b.Navigation("Pinyin");
                });
#pragma warning restore 612, 618
        }
    }
}
