// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ccex_api.Data;

#nullable disable

namespace ccex_api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241130170457_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChineseCharacterChineseCharacter", b =>
                {
                    b.Property<int>("ComponentsId")
                        .HasColumnType("integer");

                    b.Property<int>("DerivativesId")
                        .HasColumnType("integer");

                    b.HasKey("ComponentsId", "DerivativesId");

                    b.HasIndex("DerivativesId");

                    b.ToTable("ChineseCharacterChineseCharacter");
                });

            modelBuilder.Entity("ChineseCharacterPinyin", b =>
                {
                    b.Property<int>("CharsId")
                        .HasColumnType("integer");

                    b.Property<int>("PinyinsId")
                        .HasColumnType("integer");

                    b.HasKey("CharsId", "PinyinsId");

                    b.HasIndex("PinyinsId");

                    b.ToTable("ChineseCharacterPinyin");
                });

            modelBuilder.Entity("ccex_api.Models.ChineseCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Char")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.ToTable("ChineseCharacter");
                });

            modelBuilder.Entity("ccex_api.Models.Pinyin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Syllable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyllableWithToneMark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Pinyin");
                });

            modelBuilder.Entity("ChineseCharacterChineseCharacter", b =>
                {
                    b.HasOne("ccex_api.Models.ChineseCharacter", null)
                        .WithMany()
                        .HasForeignKey("ComponentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ccex_api.Models.ChineseCharacter", null)
                        .WithMany()
                        .HasForeignKey("DerivativesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChineseCharacterPinyin", b =>
                {
                    b.HasOne("ccex_api.Models.ChineseCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ccex_api.Models.Pinyin", null)
                        .WithMany()
                        .HasForeignKey("PinyinsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ccex_api.Models.ChineseCharacter", b =>
                {
                    b.HasOne("ccex_api.Models.ChineseCharacter", "Base")
                        .WithMany("Variants")
                        .HasForeignKey("BaseId");

                    b.Navigation("Base");
                });

            modelBuilder.Entity("ccex_api.Models.ChineseCharacter", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
