name: Build app and deploy on EC2

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build app and deploy on EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish --no-restore --os linux /p:Configuration=Release
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          SOURCE: "bin/Release/net9.0/linux-x64/publish"
          REMOTE_HOST: ec2-18-188-134-194.us-east-2.compute.amazonaws.com
          REMOTE_USER: ec2-user
          TARGET: "/home/ec2-user"
          SCRIPT_AFTER_REQUIRED: true
          SCRIPT_AFTER: |
            export DOTNET_ROOT=$HOME/dotnet
            export PATH=$PATH:$HOME/dotnet:$HOME/.dotnet/tools
            export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
            export NVM_DIR=$HOME/.nvm
            cd publish
            pm2 start dotnet -- ccex-api.dll --urls "http://*:5000;https://*:5001;"
