name: login to EC2

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: login to EC2
        run: ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ec2-user@ec2-3-138-36-132.us-east-2.compute.amazonaws.com