name: login to EC2

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish --no-restore --os linux
      - name: Test
        run: dotnet test --no-build --verbosity normal
  deploy:
    name: deploy to EC2 2
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          SOURCE: "bin/Release/net9.0/linux-x64"
          REMOTE_HOST: ec2-18-188-134-194.us-east-2.compute.amazonaws.com
          REMOTE_USER: ec2-user
          TARGET: "/home/ec2-user/ccex-api-ga"
